name: DOCS CICD
on: 
  workflow_dispatch:

  push:
    branches:
      - master

    paths:
      - 'src/**'
      - '*.md'
      - '**/*.md'
      - '.umirc.ts'

jobs:
  Build-Deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Restore node_modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml') }}

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20.16'

    - run: npm install --global pnpm@9
    - run: pnpm i --frozen-lockfile
    - run: pnpm build:demo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'